import { Info } from "lucide-react";
import { Card } from "@/components/ui/primitives";

/**
 * Wave 1 honesty banner: clearly marks views that still render simulated,
 * seeded data so users do not mistake them for live records.
 */

export function SimulatedBanner({ children }: { children?: React.ReactNode }) {
  return (
    <Card className="border-[var(--color-warn)]/30 bg-[var(--color-warn)]/5">
      <div className="flex items-start gap-3 p-4">
        <Info className="mt-0.5 shrink-0 text-[var(--color-warn)]" size={18} />
        <div className="flex-1">
          <p className="text-sm text-[var(--color-muted)]">
            <span className="font-semibold text-[var(--color-fg)]">Simulated data.</span>{" "}
            Figures on this page are generated by the seeded demo engine for interface demonstration.
            {children}
          </p>
        </div>
      </div>
    </Card>
  );
}
